name: NestJS API CI Staging

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
  ENV: staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: 'Setup env'
        run: cp env-example .env

      - name: Install dependencies
        run: npm i

      - name: Deploy Serverless
        run: npm run build:deploy